version: "3"
services:
  prometheus:
    container_name: dse-metric-dashboards_prometheus_1
    image: "prom/prometheus:v2.4.3"
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--storage.tsdb.retention=31d'
    ports:
      - "9090:9090"
    volumes:
      - "${PROMETHEUS_DATA_DIR:-prometheus}:/prometheus"
      - "./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml"
      - "./prometheus/tg_dse.json:/etc/prometheus/tg_dse.json"
  grafana:
    container_name: dse-metric-dashboards_grafana_1
    image: "grafana/grafana:5.3.2"
    ports:
      - "3000:3000"
    environment:
      GF_SECURITY_ADMIN_PASSWORD: admin
      GF_AUTH_ANONYMOUS_ENABLED: "true"
    volumes:
      - "${GRAFANA_DATA_DIR:-grafana}:/var/lib/grafana"
      - "./grafana/prometheus-datasource.yaml:/etc/grafana/provisioning/datasources/prometheus-datasource.yaml"
      - "./grafana/dashboards.yaml:/etc/grafana/provisioning/dashboards/dashboards.yaml"
      - "./grafana/dashboards:/var/lib/grafana/dashboards:ro"
volumes:
  grafana:
  prometheus:
